### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method flutterRestart on channel flutter_blue_plus/methods)

### ISSUE THREAD

**Issue by atishpaul2** [Sunil9162/flutter_thermal_printer#6]
Hi, I have followed all the given steps, and when i call startscan, it shows the below error - 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method flutterRestart on channel flutter_blue_plus/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      FlutterBluePlus._initFlutterBluePlus (package:flutter_blue_plus/src/flutter_blue_plus.dart:417:10)
<asynchronous suspension>

**Comment by Sunil9162** [comment]
Can you share me which platform you are using?

**Comment by atishpaul2** [comment]
Windows
